// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcDr-3g2JzmgFEGJb5yhwuUW-68YYKKuY',
    appId: '1:537810076469:web:796e6f66a35ba19132c27c',
    messagingSenderId: '537810076469',
    projectId: 'colist-e2533',
    authDomain: 'colist-e2533.firebaseapp.com',
    storageBucket: 'colist-e2533.appspot.com',
    measurementId: 'G-KZWDM6XSSE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjhd_l8eVY2z16jUo6FWtLDU1moCwF9LA',
    appId: '1:537810076469:android:c87464ec7803d83432c27c',
    messagingSenderId: '537810076469',
    projectId: 'colist-e2533',
    storageBucket: 'colist-e2533.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6-0PLhas0GIMFCLxA1Dyt5pfuKQp_Gtk',
    appId: '1:537810076469:ios:612bdaf6d545306732c27c',
    messagingSenderId: '537810076469',
    projectId: 'colist-e2533',
    storageBucket: 'colist-e2533.appspot.com',
    androidClientId:
        '537810076469-ug5l8l239o0nrcm8m1700gu0hjgkkbv1.apps.googleusercontent.com',
    iosClientId:
        '537810076469-mu0qnf4ha83dvf9k6h2lcofddmc6pp8f.apps.googleusercontent.com',
    iosBundleId: 'com.example.colist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6-0PLhas0GIMFCLxA1Dyt5pfuKQp_Gtk',
    appId: '1:537810076469:ios:612bdaf6d545306732c27c',
    messagingSenderId: '537810076469',
    projectId: 'colist-e2533',
    storageBucket: 'colist-e2533.appspot.com',
    androidClientId:
        '537810076469-ug5l8l239o0nrcm8m1700gu0hjgkkbv1.apps.googleusercontent.com',
    iosClientId:
        '537810076469-mu0qnf4ha83dvf9k6h2lcofddmc6pp8f.apps.googleusercontent.com',
    iosBundleId: 'com.example.colist',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAcDr-3g2JzmgFEGJb5yhwuUW-68YYKKuY',
    appId: '1:537810076469:web:9ee314293e4413d632c27c',
    messagingSenderId: '537810076469',
    projectId: 'colist-e2533',
    authDomain: 'colist-e2533.firebaseapp.com',
    storageBucket: 'colist-e2533.appspot.com',
    measurementId: 'G-FB6WD9TYX6',
  );
}
